[package]
name = "strangecoin"
version = "0.3.8"
edition = "2021"

[dependencies]
rusty-leveldb="4.0.0"
uuid = { version = "1.17.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.142"
sha2 = "0.10"
rand = "0.8"
eframe = "0.22"
winapi = { version = "0.3.9", features = ["windef", "winuser"] }
toml = "0.5"


[wallet]
name = "wallet1"
password = "password"
port = 8081